import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "@/components/Sidebar";
import Dashboard from "@/components/Dashboard";
import Navbar2 from "@/components/Navbar2";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* sidebar
        navbar
        Dashboard */}
        <Navbar />
        <Navbar2 />
        <Dashboard>{children}</Dashboard>
        {/* <Dashboard children={children} /> */}
      </body>
    </html>
  );
}
